#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Compiling
#

if [[ -z "$CFLAGS" ]]; then
  export CFLAGS='-O2'
fi
if [[ -z "$CXXFLAGS" ]]; then
  export CXXFLAGS='-O2'
fi
if [[ -z "$PYTHON_CONFIGURE_OPTS" ]]; then
  export PYTHON_CONFIGURE_OPTS='--enable-shared --enable-unicode=ucs4'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
typeset -gUT CPATH cpath
typeset -gUT LIBRARY_PATH library_path
typeset -gUT INFOPATH infopath
typeset -gU MANPATH manpath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /opt/local/{bin,sbin}
  $path
  ~/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
#
if [[ -z "$TMPDIR" ]]; then
  export TMPDIR="/tmp/zsh-$UID"
fi

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$(echo "$LOGNAME" | tr -d ' ')"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


case `uname` in
    *Darwin*)
        export ARDUINO_DIR='/Applications/Arduino.app/Contents/Resources/Java'
        export ARDMK_DIR='~/bin/Arduino-Makefile'
        path=(/usr/local/texlive/2016/bin/x86_64-darwin $path)
        path=($path ~/Library/Python/3.6/bin ~/.gem/ruby/2.0.0/bin ~/bin/Arduino-Makefile/bin /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ /Applications/MATLAB_R2010b.app/bin/ /usr/local/CrossPack-AVR/bin)
        source ~/.iterm2_shell_integration.`basename $SHELL`
        export PYOPENCL_CTX='2'
        ;;
    *Linux*)
        export PYENV_ROOT="${HOME}/.pyenv"
        if [ -d "${PYENV_ROOT}" ]; then
            path=("${PYENV_ROOT}/bin" $path)
            eval "$(pyenv init -)"
        fi
        path=(/usr/local/texlive/2015/bin/x86_64-linux $path)
        infopath=(/usr/local/texlive/2015/texmf-dist/doc/info $infopath)
        manpath=(/usr/local/texlive/2015/texmf-dist/doc/man $manpath)
        export PYOPENCL_CTX='0'
        ;;
    *NT*)
        path=(/c/Program\ Files\ \(x86\)/GnuPG/bin $path)
esac

infopath=(/usr/local/texlive/2016/texmf-dist/doc/info $infopath)
manpath=(/usr/local/texlive/2016/texmf-dist/doc/man $manpath)

cpath=(/opt/local/include $cpath)
library_path=(/opt/local/lib $library_path)
